# Generated by Django 6.0.3 on 2026-03-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='nationlity',
            new_name='nationality',
        ),
    ]
