# Generated by Django 6.0.3 on 2026-03-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nationlity_actor_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='released',
            field=models.DateField(blank=True, null=True),
        ),
    ]
